on:
  push:
    branches:
      - future


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: future
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/assets/css

      - name: Compile CSS from SCSS files style.css
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: ./style.scss
          destination: /tmp/assets/css/style.css

      - name: Compile CSS from SCSS files top01.css
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: ./top01.scss
          destination: /tmp/assets/css/top01.css

      - name: Compile CSS from SCSS files top02.css
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: ./top02.scss
          destination: /tmp/assets/css/top02.css


      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -rlOtcv --delete --exclude-from=.rsyncignore -e "ssh -p 2222 -i id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" . ${{secrets.RSYNC_COMMAND}}
 