on:
  push:
    branches:
      - future


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: future
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: ./style.scss
          destination: /tmp/assets/css/style.css

      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" ＞ key ＆＆ chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        run: rsync -azrP -e "ssh -p 2222 -o StrictHostKeyChecking=no" ./* ${{secrets.RSYNC_COMMAND}}
 